=== aws/serverless-application-model/samtranslator/validator/sam_schema/schema_new.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "AWSTemplateFormatVersion": {
      "enum": [
        "2010-09-09"
      ],
      "type": "string"
    },
    "Conditions": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "intrinsic"
        }
      },
      "type": "object"
    },
    "Description": {
      "description": "Template description",
      "maxLength": 1024,
      "type": "string"
    },
    "Globals": {
      "type": "object"
    },
    "Mappings": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Metadata": {
      "type": "object"
    },
    "Outputs": {
      "additionalProperties": false,
      "maxProperties": 60,
      "minProperties": 1,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Parameters": {
      "additionalProperties": false,
      "maxProperties": 50,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "$ref": "parameter.json#/definitions/Parameter"
        }
      },
      "type": "object"
    },
    "Resources": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "allOf": [
            {
              "$ref": "api.json#/definitions/AWS::Serverless::Api"
            },
            {
              "if": {
                "properties": {
                  "Type": {
                    "pattern": "^Custom::"
                  }
                }
              },
              "then": {
                "properties": {
                  "Type": {
                    "pattern": "^Custom::[a-zA-Z0-9]+$",
                    "patternError": "must use format Custom::X"
                  }
                }
              },
              "else": {
                "properties": {
                  "Type": {
                    "pattern": "^[a-zA-Z0-9]+::[a-zA-Z0-9]+::[a-zA-Z0-9]+$",
                    "patternError": "must use format X::Y::Z"
                  }
                }
              }
            },
            {
              "if": {
                "properties": {
                  "Type": {
                    "pattern": "^AWS::Serverless::"
                  }
                }
              },
              "then": {
                "properties": {
                  "Type": {
                    "enum": [
                      "AWS::Serverless::Api",
                      "AWS::Serverless::Application",
                      "AWS::Serverless::Function",
                      "AWS::Serverless::WebFunction",
                      "AWS::Serverless::HttpApi",
                      "AWS::Serverless::WebSocketApi",
                      "AWS::Serverless::LayerVersion",
                      "AWS::Serverless::SimpleTable",
                      "AWS::Serverless::StateMachine",
                      "AWS::Serverless::Connector",
                      "AWS::Serverless::GraphQLApi"                    ]
                  }
                }
              }
            }
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "Transform": {
      "type": [
        "string",
        "array"
      ],
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "Resources"
  ],
  "type": "object"
}

=== aws/serverless-application-model/tests/translator/output/aws-cn/api_custom_domain_private_endpoint_without_policy.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Sample SAM Template for a simple serverless application",
  "Parameters": {
    "CertificateArn": {
      "Default": "arn:aws:acm:us-east-1:123456789012:certificate/4ba8fce1-abcd-4717-9c34-11bfd24372ba",
      "Type": "String"
    },
    "DomainName": {
      "Default": "sam.apigateway.com",
      "Type": "String"
    },
    "HostedZoneId": {
      "Default": "Z012334",
      "Type": "String"
    },
    "VpcEndpointId": {
      "Default": "vpce-123123123123123",
      "Type": "String"
    }
  },
  "Resources": {
    "ApiGatewayDomainNameV2f6d6317296": {
      "Properties": {
        "CertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/4ba8fce1-abcd-4717-9c34-11bfd24372ba",
        "DomainName": "sam.apigateway.com",
        "EndpointConfiguration": {
          "Types": [
            "PRIVATE"
          ]
        }
      },
      "Type": "AWS::ApiGateway::DomainNameV2"
    },
    "MyApi": {
      "Properties": {
        "Body": {
          "info": {
            "title": {
              "Ref": "AWS::StackName"
            },
            "version": "1.0"
          },
          "openapi": "3.0.1",
          "paths": {}
        },
        "EndpointConfiguration": {
          "Types": [
            "PRIVATE"
          ],
          "VpcEndpointIds": [
            {
              "Ref": "VpcEndpointId"
            }
          ]
        },
        "Parameters": {
          "endpointConfigurationTypes": "PRIVATE"
        },
        "Policy": {
          "Statement": [
            {
              "Action": "execute-api:Invoke",
              "Effect": "Allow",
              "Principal": "*",
              "Resource": "execute-api:/*"
            },
            {
              "Action": "execute-api:Invoke",
              "Condition": {
                "StringNotEquals": {
                  "aws:SourceVpce": {
                    "Ref": "VpcEndpointId"
                  }
                }
              },
              "Effect": "Deny",
              "Principal": "*",
              "Resource": "execute-api:/*"
            }
          ],
          "Version": "2012-10-17"
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "MyApiDeploymentdbd67416a9": {
      "Properties": {
        "Description": "RestApi deployment id: dbd67416a94d411fe2930d26ea838f562f2b45fd",
        "RestApiId": {
          "Ref": "MyApi"
        }
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "MyApiProdStage": {
      "Properties": {
        "DeploymentId": {
          "Ref": "MyApiDeploymentdbd67416a9"
        },
        "RestApiId": {
          "Ref": "MyApi"
        },
        "StageName": "Prod"
      },
      "Type": "AWS::ApiGateway::Stage"
    },
    "MyApigetBasePathMapping": {
      "Properties": {
        "BasePath": "get",
        "DomainNameArn": {
          "Ref": "ApiGatewayDomainNameV2f6d6317296"
        },
        "RestApiId": {
          "Ref": "MyApi"
        },
        "Stage": {
          "Ref": "MyApiProdStage"
        }
      },
      "Type": "AWS::ApiGateway::BasePathMappingV2"
    },
    "RecordSetGroup486a9be065": {
      "Properties": {
        "HostedZoneId": "HostedZoneId",
        "RecordSets": [
          {
            "AliasTarget": {
              "DNSName": "VPCEndpointDomainName",
              "HostedZoneId": "VPCEndpointHostedZoneId"
            },
            "Name": "sam.apigateway.com",
            "Type": "A"
          },
          {
            "AliasTarget": {
              "DNSName": "VPCEndpointDomainName",
              "HostedZoneId": "VPCEndpointHostedZoneId"
            },
            "Name": "sam.apigateway.com",
            "Type": "AAAA"
          }
        ]
      },
      "Type": "AWS::Route53::RecordSetGroup"
    }
  }
}

=== aws/serverless-application-model/tests/translator/output/aws-cn/network_connector_with_intrinsics.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "NetworkConnector with intrinsic functions in VpcConfig",
  "Parameters": {
    "SecurityGroupId": {
      "Type": "String"
    },
    "SubnetId": {
      "Type": "String"
    }
  },
  "Resources": {
    "MyNetworkConnector": {
      "Properties": {
        "Configuration": {
          "VpcEgressConfiguration": {
            "AssociatedComputeResourceTypes": [
              "MicroVm"
            ],
            "NetworkProtocol": "IPv4",
            "SecurityGroupIds": [
              {
                "Ref": "SecurityGroupId"
              }
            ],
            "SubnetIds": [
              {
                "Ref": "SubnetId"
              }
            ]
          }
        },
        "OperatorRole": {
          "Fn::GetAtt": [
            "MyNetworkConnectorOperatorRole",
            "Arn"
          ]
        },
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::Lambda::NetworkConnector"
    },
    "MyNetworkConnectorOperatorRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws-cn:iam::aws:policy/AWSLambdaNetworkConnectorOperatorPolicy"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    }
  }
}

=== aws/serverless-application-model/tests/translator/output/api_custom_domain_private_endpoint_route53_hostedzonename.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Sample SAM Template for a simple serverless application",
  "Parameters": {
    "CertificateArn": {
      "Default": "arn:aws:acm:us-east-1:123456789012:certificate/4ba8fce1-abcd-4717-9c34-11bfd24372ba",
      "Type": "String"
    },
    "DomainName": {
      "Default": "sam.apigateway.com",
      "Type": "String"
    },
    "HostedZoneId": {
      "Default": "Z012334",
      "Type": "String"
    },
    "VpcEndpointId": {
      "Default": "vpce-123123123123123",
      "Type": "String"
    }
  },
  "Resources": {
    "ApiGatewayDomainNameV2f6d6317296": {
      "Properties": {
        "CertificateArn": "arn:aws:acm:us-east-1:123456789012:certificate/4ba8fce1-abcd-4717-9c34-11bfd24372ba",
        "DomainName": "sam.apigateway.com",
        "EndpointConfiguration": {
          "Types": [
            "PRIVATE"
          ]
        },
        "Policy": {
          "Statement": [
            {
              "Action": "execute-api:Invoke",
              "Effect": "Allow",
              "Principal": "*",
              "Resource": "execute-api:/*"
            },
            {
              "Action": "execute-api:Invoke",
              "Condition": {
                "StringNotEquals": {
                  "aws:SourceVpce": "vpce-123123123123123"
                }
              },
              "Effect": "Deny",
              "Principal": "*",
              "Resource": "execute-api:/*"
            }
          ],
          "Version": "2012-10-17"
        }
      },
      "Type": "AWS::ApiGateway::DomainNameV2"
    },
    "MyApi": {
      "Properties": {
        "Body": {
          "info": {
            "title": {
              "Ref": "AWS::StackName"
            },
            "version": "1.0"
          },
          "openapi": "3.0.1",
          "paths": {}
        },
        "EndpointConfiguration": {
          "Types": [
            "PRIVATE"
          ],
          "VpcEndpointIds": [
            {
              "Ref": "VpcEndpointId"
            }
          ]
        },
        "Parameters": {
          "endpointConfigurationTypes": "PRIVATE"
        },
        "Policy": {
          "Statement": [
            {
              "Action": "execute-api:Invoke",
              "Effect": "Allow",
              "Principal": "*",
              "Resource": "execute-api:/*"
            },
            {
              "Action": "execute-api:Invoke",
              "Condition": {
                "StringNotEquals": {
                  "aws:SourceVpce": {
                    "Ref": "VpcEndpointId"
                  }
                }
              },
              "Effect": "Deny",
              "Principal": "*",
              "Resource": "execute-api:/*"
            }
          ],
          "Version": "2012-10-17"
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "MyApiDeploymentd5e9004dee": {
      "Properties": {
        "Description": "RestApi deployment id: d5e9004dee57490c19220f944a5f0a204c041c13",
        "RestApiId": {
          "Ref": "MyApi"
        }
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "MyApiProdStage": {
      "Properties": {
        "DeploymentId": {
          "Ref": "MyApiDeploymentd5e9004dee"
        },
        "RestApiId": {
          "Ref": "MyApi"
        },
        "StageName": "Prod"
      },
      "Type": "AWS::ApiGateway::Stage"
    },
    "MyApigetBasePathMapping": {
      "Properties": {
        "BasePath": "get",
        "DomainNameArn": {
          "Ref": "ApiGatewayDomainNameV2f6d6317296"
        },
        "RestApiId": {
          "Ref": "MyApi"
        },
        "Stage": {
          "Ref": "MyApiProdStage"
        }
      },
      "Type": "AWS::ApiGateway::BasePathMappingV2"
    },
    "RecordSetGroup456ebaf280": {
      "Properties": {
        "HostedZoneName": "www.my-domain.com.",
        "RecordSets": [
          {
            "AliasTarget": {
              "DNSName": "VPCEndpointDomainName",
              "HostedZoneId": "VPCEndpointHostedZoneId"
            },
            "Name": "sam.apigateway.com",
            "Type": "A"
          }
        ]
      },
      "Type": "AWS::Route53::RecordSetGroup"
    }
  }
}

=== aws/serverless-application-model/tests/translator/output/capacity_provider_with_intrinsics.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "CapacityProvider with intrinsic functions test",
  "Parameters": {
    "AllowedInstanceType": {
      "Default": "c5.xlarge",
      "Type": "String"
    },
    "Architecture": {
      "Default": "arm64",
      "Type": "String"
    },
    "ArchitecturesList": {
      "Default": "x86_64",
      "Type": "List<String>"
    },
    "CapacityProviderName": {
      "Default": "intrinsic-capacity-provider",
      "Type": "String"
    },
    "ExcludedInstanceTypeList": {
      "Default": "t2.micro, c5.xlarge",
      "Type": "List<String>"
    },
    "KmsKeyArn": {
      "Default": "arn:aws:kms:us-east-1:123456789012:key/abcd1234-ef56-gh78-ij90-klmnopqrstuv",
      "Type": "String"
    },
    "MaxVCpuCount": {
      "Default": 10,
      "Type": "Number"
    },
    "SecurityGroupId": {
      "Default": "sg-0a1e1457229da0f74",
      "Type": "String"
    },
    "SecurityGroupIdList": {
      "Default": "sg-0a1e1457229da0f74",
      "Type": "List<AWS::EC2::SecurityGroup::Id>"
    },
    "SubnetId": {
      "Default": "subnet-01e6344879fd06036",
      "Type": "String"
    },
    "SubnetIdList": {
      "Default": "subnet-01e6344879fd06036",
      "Type": "List<AWS::EC2::Subnet::Id>"
    },
    "TargetCPU": {
      "Default": 75.0,
      "Type": "Number"
    },
    "TargetMemory": {
      "Default": 81.2,
      "Type": "Number"
    }
  },
  "Resources": {
    "IntrinsicCapacityProvider": {
      "Properties": {
        "CapacityProviderName": {
          "Ref": "CapacityProviderName"
        },
        "CapacityProviderScalingConfig": {
          "MaxVCpuCount": {
            "Ref": "MaxVCpuCount"
          },
          "ScalingMode": "Manual",
          "ScalingPolicies": [
            {
              "PredefinedMetricType": "LambdaCapacityProviderAverageCPUUtilization",
              "TargetValue": {
                "Ref": "TargetCPU"
              }
            }
          ]
        },
        "InstanceRequirements": {
          "AllowedInstanceTypes": [
            {
              "Ref": "AllowedInstanceType"
            },
            {
              "Fn::Join": [
                ".",
                [
                  "c5",
                  "2xlarge"
                ]
              ]
            },
            "c5.large"
          ],
          "Architectures": [
            {
              "Ref": "Architecture"
            }
          ]
        },
        "KmsKeyArn": {
          "Ref": "KmsKeyArn"
        },
        "PermissionsConfig": {
          "CapacityProviderOperatorRoleArn": {
            "Fn::GetAtt": [
              "IntrinsicCapacityProviderOperatorRole",
              "Arn"
            ]
          }
        },
        "Tags": [
          {
            "Key": "Environment",
            "Value": {
              "Fn::Sub": "${AWS::StackName}-environment"
            }
          },
          {
            "Key": "Team",
            "Value": {
              "Fn::Sub": "${AWS::StackName}-team"
            }
          },
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ],
        "VpcConfig": {
          "SecurityGroupIds": [
            {
              "Ref": "SecurityGroupId"
            }
          ],
          "SubnetIds": [
            {
              "Ref": "SubnetId"
            }
          ]
        }
      },
      "Type": "AWS::Lambda::CapacityProvider"
    },
    "IntrinsicCapacityProviderOperatorRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/AWSLambdaManagedEC2ResourceOperator"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    },
    "IntrinsicCapacityProviderTwo": {
      "Properties": {
        "CapacityProviderScalingConfig": {
          "MaxVCpuCount": {
            "Ref": "MaxVCpuCount"
          },
          "ScalingMode": "Manual",
          "ScalingPolicies": [
            {
              "PredefinedMetricType": "LambdaCapacityProviderAverageCPUUtilization",
              "TargetValue": {
                "Ref": "TargetCPU"
              }
            }
          ]
        },
        "InstanceRequirements": {
          "Architectures": {
            "Ref": "ArchitecturesList"
          },
          "ExcludedInstanceTypes": {
            "Ref": "ExcludedInstanceTypeList"
          }
        },
        "KmsKeyArn": {
          "Ref": "KmsKeyArn"
        },
        "PermissionsConfig": {
          "CapacityProviderOperatorRoleArn": {
            "Fn::GetAtt": [
              "IntrinsicCapacityProviderTwoOperatorRole",
              "Arn"
            ]
          }
        },
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ],
        "VpcConfig": {
          "SecurityGroupIds": {
            "Ref": "SecurityGroupIdList"
          },
          "SubnetIds": {
            "Ref": "SubnetIdList"
          }
        }
      },
      "Type": "AWS::Lambda::CapacityProvider"
    },
    "IntrinsicCapacityProviderTwoOperatorRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/AWSLambdaManagedEC2ResourceOperator"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    }
  }
}

=== aws/serverless-application-model/tests/translator/output/aws-us-gov/capacity_provider_managed_resource_tags.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Test ManagedResourceTags - explicit tags configuration",
  "Parameters": {
    "Environment": {
      "Default": "Production",
      "Type": "String"
    }
  },
  "Resources": {
    "CpInheritsGlobal": {
      "Properties": {
        "PermissionsConfig": {
          "CapacityProviderOperatorRoleArn": {
            "Fn::GetAtt": [
              "CpInheritsGlobalOperatorRole",
              "Arn"
            ]
          }
        },
        "PropagateTags": {
          "ExplicitTags": [
            {
              "Key": "GlobalTag",
              "Value": "shared-value"
            }
          ],
          "Mode": "Explicit"
        },
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ],
        "VpcConfig": {
          "SecurityGroupIds": [
            "sg-11111111"
          ],
          "SubnetIds": [
            "subnet-11111111"
          ]
        }
      },
      "Type": "AWS::Lambda::CapacityProvider"
    },
    "CpInheritsGlobalOperatorRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws-us-gov:iam::aws:policy/AWSLambdaManagedEC2ResourceOperator"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    },
    "CpNoManagedResourceTags": {
      "Properties": {
        "PermissionsConfig": {
          "CapacityProviderOperatorRoleArn": {
            "Fn::GetAtt": [
              "CpNoManagedResourceTagsOperatorRole",
              "Arn"
            ]
          }
        },
        "PropagateTags": {
          "ExplicitTags": [
            {
              "Key": "GlobalTag",
              "Value": "shared-value"
            }
          ],
          "Mode": "Explicit"
        },
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ],
        "VpcConfig": {
          "SecurityGroupIds": [
            "sg-33333333"
          ],
          "SubnetIds": [
            "subnet-33333333"
          ]
        }
      },
      "Type": "AWS::Lambda::CapacityProvider"
    },
    "CpNoManagedResourceTagsOperatorRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws-us-gov:iam::aws:policy/AWSLambdaManagedEC2ResourceOperator"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    },
    "CpOverrideWithExplicitTags": {
      "Properties": {
        "PermissionsConfig": {
          "CapacityProviderOperatorRoleArn": {
            "Fn::GetAtt": [
              "CpOverrideWithExplicitTagsOperatorRole",
              "Arn"
            ]
          }
        },
        "PropagateTags": {
          "ExplicitTags": [
            {
              "Key": "GlobalTag",
              "Value": "shared-value"
            },
            {
              "Key": "Environment",
              "Value": {
                "Ref": "Environment"
              }
            },
            {
              "Key": "Team",
              "Value": {
                "Fn::Sub": "${AWS::StackName}-tooling"
              }
            }
          ],
          "Mode": "Explicit"
        },
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ],
        "VpcConfig": {
          "SecurityGroupIds": [
            "sg-22222222"
          ],
          "SubnetIds": [
            "subnet-22222222"
          ]
        }
      },
      "Type": "AWS::Lambda::CapacityProvider"
    },
    "CpOverrideWithExplicitTagsOperatorRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws-us-gov:iam::aws:policy/AWSLambdaManagedEC2ResourceOperator"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    }
  }
}
