=== aws/serverless-application-model/samtranslator/validator/sam_schema/schema_new.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "AWSTemplateFormatVersion": {
      "enum": [
        "2010-09-09"
      ],
      "type": "string"
    },
    "Conditions": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "intrinsic"
        }
      },
      "type": "object"
    },
    "Description": {
      "description": "Template description",
      "maxLength": 1024,
      "type": "string"
    },
    "Globals": {
      "type": "object"
    },
    "Mappings": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Metadata": {
      "type": "object"
    },
    "Outputs": {
      "additionalProperties": false,
      "maxProperties": 60,
      "minProperties": 1,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "type": "object"
        }
      },
      "type": "object"
    },
    "Parameters": {
      "additionalProperties": false,
      "maxProperties": 50,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "$ref": "parameter.json#/definitions/Parameter"
        }
      },
      "type": "object"
    },
    "Resources": {
      "additionalProperties": false,
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "allOf": [
            {
              "$ref": "api.json#/definitions/AWS::Serverless::Api"
            },
            {
              "if": {
                "properties": {
                  "Type": {
                    "pattern": "^Custom::"
                  }
                }
              },
              "then": {
                "properties": {
                  "Type": {
                    "pattern": "^Custom::[a-zA-Z0-9]+$",
                    "patternError": "must use format Custom::X"
                  }
                }
              },
              "else": {
                "properties": {
                  "Type": {
                    "pattern": "^[a-zA-Z0-9]+::[a-zA-Z0-9]+::[a-zA-Z0-9]+$",
                    "patternError": "must use format X::Y::Z"
                  }
                }
              }
            },
            {
              "if": {
                "properties": {
                  "Type": {
                    "pattern": "^AWS::Serverless::"
                  }
                }
              },
              "then": {
                "properties": {
                  "Type": {
                    "enum": [
                      "AWS::Serverless::Api",
                      "AWS::Serverless::Application",
                      "AWS::Serverless::Function",
                      "AWS::Serverless::WebFunction",
                      "AWS::Serverless::HttpApi",
                      "AWS::Serverless::WebSocketApi",
                      "AWS::Serverless::LayerVersion",
                      "AWS::Serverless::SimpleTable",
                      "AWS::Serverless::StateMachine",
                      "AWS::Serverless::Connector",
                      "AWS::Serverless::GraphQLApi"                    ]
                  }
                }
              }
            }
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "Transform": {
      "type": [
        "string",
        "array"
      ],
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "Resources"
  ],
  "type": "object"
}

=== aws/serverless-application-model/tests/translator/output/definition_body_intrinsics_support.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Conditions": {
    "FalseCondition": {
      "Fn::Equals": [
        {
          "Ref": "AWS::AccountId"
        },
        "myAccountId"
      ]
    }
  },
  "Description": "DefinitionBody currently only supports intrinsics when SwaggerEditor/OpenApiEditor is not used (as of 2022-05-30). Let's add tests to make sure we keep this support, because we've had a regression where we accidentally removed this intrinsics support by using the SwaggerEditor. Note that the only supported intrinsic function for DefinitionBody is Fn::If. Other intrinsics are not supported because they don't resolve to dictionary. \n",
  "Resources": {
    "HttpApiIfIntrinsicAndNoOpenApiEditor": {
      "Properties": {
        "Body": {
          "Fn::If": [
            "FalseCondition",
            {
              "info": {
                "title": {
                  "Fn::Sub": "${AWS::StackName}-Api"
                }
              },
              "openapi": "3.0",
              "paths": {
                "/post": {
                  "post": {
                    "x-amazon-apigateway-integration": {
                      "httpMethod": "POST",
                      "payloadFormatVersion": "1.0",
                      "type": "aws_proxy",
                      "uri": "https://www.alphavantage.co/"
                    }
                  }
                }
              }
            },
            {
              "info": {
                "title": {
                  "Fn::Sub": "${AWS::StackName}-Api"
                }
              },
              "openapi": "3.0",
              "paths": {
                "/post": {
                  "post": {
                    "x-amazon-apigateway-integration": {
                      "httpMethod": "POST",
                      "payloadFormatVersion": "1.0",
                      "type": "aws_proxy",
                      "uri": "https://www.otheruri.co/"
                    }
                  }
                }
              }
            }
          ]
        }
      },
      "Type": "AWS::ApiGatewayV2::Api"
    },
    "HttpApiIfIntrinsicAndNoOpenApiEditorprodStage": {
      "Properties": {
        "ApiId": {
          "Ref": "HttpApiIfIntrinsicAndNoOpenApiEditor"
        },
        "AutoDeploy": true,
        "StageName": "prod"
      },
      "Type": "AWS::ApiGatewayV2::Stage"
    },
    "RestApiIfIntrinsicAndNoSwaggerEditor": {
      "Properties": {
        "Body": {
          "Fn::If": [
            "FalseCondition",
            {
              "info": {
                "title": {
                  "Fn::Sub": "${AWS::StackName}-Api"
                }
              },
              "paths": {
                "/post": {
                  "post": {
                    "x-amazon-apigateway-integration": {
                      "httpMethod": "POST",
                      "payloadFormatVersion": "1.0",
                      "type": "aws_proxy",
                      "uri": "https://www.alphavantage.co/"
                    }
                  }
                }
              },
              "swagger": "2.0"
            },
            {
              "info": {
                "title": {
                  "Fn::Sub": "${AWS::StackName}-Api"
                }
              },
              "paths": {
                "/post": {
                  "post": {
                    "x-amazon-apigateway-integration": {
                      "httpMethod": "POST",
                      "payloadFormatVersion": "1.0",
                      "type": "aws_proxy",
                      "uri": "https://www.otheruri.co/"
                    }
                  }
                }
              },
              "swagger": "2.0"
            }
          ]
        }
      },
      "Type": "AWS::ApiGateway::RestApi"
    },
    "RestApiIfIntrinsicAndNoSwaggerEditorDeployment2f0411dccd": {
      "Properties": {
        "Description": "RestApi deployment id: 2f0411dccde517dcb5c82d3848dbc431e7479ebc",
        "RestApiId": {
          "Ref": "RestApiIfIntrinsicAndNoSwaggerEditor"
        },
        "StageName": "Stage"
      },
      "Type": "AWS::ApiGateway::Deployment"
    },
    "RestApiIfIntrinsicAndNoSwaggerEditorprodStage": {
      "Properties": {
        "DeploymentId": {
          "Ref": "RestApiIfIntrinsicAndNoSwaggerEditorDeployment2f0411dccd"
        },
        "RestApiId": {
          "Ref": "RestApiIfIntrinsicAndNoSwaggerEditor"
        },
        "StageName": "prod"
      },
      "Type": "AWS::ApiGateway::Stage"
    }
  }
}

=== aws/serverless-application-model/tests/translator/output/aws-cn/schema_validation_4.json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Conditions": {
    "CreateProdResources": {
      "Fn::Equals": [
        {
          "Ref": "InstanceTypeParameter"
        },
        "prod"
      ]
    }
  },
  "Description": "Some description",
  "Outputs": {
    "BackupLoadBalancerDNSName": {
      "Condition": "CreateProdResources",
      "Description": "The DNSName of the backup load balancer",
      "Value": {
        "Ref": "Function"
      }
    }
  },
  "Parameters": {
    "InstanceTypeParameter": {
      "AllowedValues": [
        "t2.micro",
        "m1.small",
        "m1.large"
      ],
      "Default": "t2.micro",
      "Description": "Enter t2.micro, m1.small, or m1.large. Default is t2.micro.",
      "Type": "String"
    }
  },
  "Resources": {
    "Bucket": {
      "Condition": "CreateProdResources",
      "Type": "AWS::S3::Bucket"
    },
    "Function": {
      "Properties": {
        "Code": {
          "S3Bucket": "my-bucket",
          "S3Key": "function.zip"
        },
        "Handler": "index.handler",
        "Role": "arn:aws:iam::123456789012:role/lambda-role",
        "Runtime": "nodejs12.x",
        "Timeout": 5,
        "TracingConfig": {
          "Mode": "Active"
        },
        "VpcConfig": {
          "SecurityGroupIds": [
            "sg-085912345678492fb"
          ],
          "SubnetIds": [
            "subnet-071f712345678e7c8",
            "subnet-07fd123456788a036"
          ]
        }
      },
      "Type": "AWS::Lambda::Function"
    },
    "MyInstance": {
      "Properties": {
        "BlockDeviceMappings": [
          {
            "DeviceName": "/dev/sdm",
            "Ebs": {
              "DeleteOnTermination": false,
              "Iops": 200,
              "VolumeSize": 20,
              "VolumeType": "io1"
            }
          },
          {
            "DeviceName": "/dev/sdk",
            "NoDevice": {}
          }
        ],
        "ImageId": "ami-79fd7eee",
        "KeyName": "testkey"
      },
      "Type": "AWS::EC2::Instance"
    },
    "MyTable": {
      "Properties": {
        "AttributeDefinitions": [
          {
            "AttributeName": "id",
            "AttributeType": "S"
          }
        ],
        "BillingMode": "PAY_PER_REQUEST",
        "KeySchema": [
          {
            "AttributeName": "id",
            "KeyType": "HASH"
          }
        ]
      },
      "Type": "AWS::DynamoDB::Table"
    },
    "OtherFunction": {
      "Properties": {
        "Code": {
          "ZipFile": "bar"
        },
        "Environment": {
          "Variables": {
            "Some": "variable"
          }
        },
        "Handler": "foo",
        "Role": {
          "Fn::GetAtt": [
            "OtherFunctionRole",
            "Arn"
          ]
        },
        "Runtime": "python3.8",
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::Lambda::Function"
    },
    "OtherFunctionRole": {
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ],
          "Version": "2012-10-17"
        },
        "ManagedPolicyArns": [
          "arn:aws-cn:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        ],
        "Tags": [
          {
            "Key": "lambda:createdBy",
            "Value": "SAM"
          }
        ]
      },
      "Type": "AWS::IAM::Role"
    }
  }
}
